apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postmark-ingress
  namespace: postmark
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: postmark.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postmark-api-lb
                port:
                  number: 80
                  